name: Linux CI

on:
  push:
    branches: [ "devel", "main" ]
  pull_request:
    branches: [ "devel", "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟥', arch: "x86_64",  os: "ubuntu-22.04" }
          - { icon: '🟩', arch: "aarch64", os: "ubuntu-24.04-arm" }
    runs-on: ${{ matrix.os }}
    name: 🚧${{ matrix.icon }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: '${{ matrix.icon }} Install Qt'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.1'

    - name: '${{ matrix.icon }} Configure CMake'
      id: configuration
      run: cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_INSTALL_PREFIX=/usr
        -DCMAKE_INSTALL_LIBDIR=lib
        -DCMAKE_INSTALL_RPATH="\$ORIGIN/../lib"

    - name: '${{ matrix.icon }} Build'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Install'
      env:
        DESTDIR: ${{github.workspace}}/build/createQtAppImage-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppDir
      run: cmake --install build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Upload AppImage'
      env:
        INSTALL_LOCATION: createQtAppImage-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppImage
      uses: actions/upload-artifact@v7
      with:
        name: ${{env.INSTALL_LOCATION}}
        path: ${{github.workspace}}/build/${{env.INSTALL_LOCATION}}
        retention-days: 90
        overwrite: true
        archive: false
